services:
  teamcity-server:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs
    networks:
      - cicd-network

  teamcity-agent:
    build: ./agent
    container_name: teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=teamcity-agent
    volumes:
      - teamcity-agent-config:/data/teamcity_agent/conf
    networks:
      - cicd-network
    depends_on:
      - teamcity-server


  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - cicd-network

networks:
  cicd-network:
      driver: bridge


volumes:
  teamcity-data:
  teamcity-logs:
  teamcity-agent-config:
  sql-server-data: